name: Build Snapshot Release

on:
  push:
    branches:
      - 'development'

jobs:
  call-workflow:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      doTests: true
      snapshot: true
